###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_info"
}

###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{ 
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_block",
  "params": { 
    "height": 3546761
  } 
}

###
POST https://xmr3.doggett.tech:18089/get_transactions
Content-Type: application/json

{
  "txs_hashes": [
    "22b22bb5201cfd544215efe7e5ee045f875aeb38ed93f782d9fb1acb0e2ffdff"
  ],
  "decode_as_json": true
}