###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_info"
}

###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{ 
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_block",
  "params": { 
    "height": 3546761
  } 
}

###
POST https://xmr3.doggett.tech:18089/get_transactions
Content-Type: application/json

{
  "txs_hashes": [
    "56d71a0fe59ba0f61dc32d062fbec8de9c8fcdb9ab947f965cb75afa158e84ac"
  ],
  "decode_as_json": false
}