###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_info"
}

###
POST https://xmr.unshakled.net:443/json_rpc
Content-Type: application/json

{ 
  "jsonrpc": "2.0",
  "id": "0",
  "method": "get_block",
  "params": { "height": 3492045 }
}

###
POST https://xmr.unshakled.net:443/get_transactions
Content-Type: application/json

{
  "txs_hashes": [
    "8B891C0352014EA6687A0B51B8128EC238B26C9BD523AA1554DEF1078D822222"
  ],
  "decode_as_json": true
}